### ISSUE TITLE
Broken link 

### ISSUE THREAD

**Issue by rholling** [SovereignCloudStack/.github#15]
Hi,
My colleauge tried to get information through the FAQ "I want to use the SCS in my company and build my own cloud! Where do I start?", but it ends up in a broken link.

https://docs.scs.community/docs/faq/
Then: Link to Guide (https://doc.scs.community/standards/)

If I'm wrong, Max, refer to another person, please.

Regards,
Robert

**Comment by maxwolfs** [comment]
fixed by https://github.com/SovereignCloudStack/docs/pull/140
